### ISSUE TITLE
Add Unit tests for `FakerBot::Renderer`

### ISSUE THREAD

**Issue by akabiru** [akabiru/faker-bot#11]
`spec/fakerbot/renderer_spec.rb`

**Comment by MikaelAbehsera** [comment]
@akabiru is this still open, I'm new and would like to help!

**Comment by akabiru** [comment]
Hey @MikaelAbehsera , sure! Got for it! 🙂

**Comment by akabiru** [comment]
Hey @MikaelAbehsera , just checking in on this- feel free to let me know if sth is unclear.

**Comment by akabiru** [comment]
Since I haven't heard from you, I'm afraid I've gone ahead and resolved this as I had some time on my hands. 🙂
