### ISSUE TITLE
Improve Search

### ISSUE THREAD

**Issue by akabiru** [akabiru/faker-bot#13]
It's worrying that search cannot match "first_name" to "firstname" - maybe look into a different approach that's more "fuzzy like"

![screen shot 2018-10-05 at 15 53 34](https://user-images.githubusercontent.com/17295175/46537755-bb7ffe80-c8ba-11e8-81ee-d795e06eb333.jpg)

**Comment by codealchemy** [comment]
Is not matching on the underscore the only issue, or are there other patterns that should be considered?

**Comment by akabiru** [comment]
Hey Alex, the underscore bit was an example- we should definitely look into improving search. At the moment, it’s just a standard regex match.

**Comment by codealchemy** [comment]
Got it - one option would be to expand on the regex / do multiple passes attempts matching, which would avoid any new dependencies but also might not be quite 'fuzzy' enough depending on what's needed.

Another would be to consider introducing a library like [`amatch`](https://github.com/flori/amatch) or [`fuzzy-string-match`](https://github.com/kiyoka/fuzzy-string-match), though that would bring with it things like confidence levels or extending `String`, and it wasn't clear if this project would be open to those kinds of changes.

Thoughts?

**Comment by akabiru** [comment]
FWIW, I’m open to introducing new libraries. I’ve had a quick look at amatch and fuzzy-string-match and they look good. Are you Ok to take lead on this issue? 🙂

**Comment by codealchemy** [comment]
@akabiru Sure thing - I'll take a pass at it within the next few days
