### ISSUE TITLE
Faker issue: Byebug reporting error at require "faker" 

### ISSUE THREAD

**Issue by robertemaxwell** [akabiru/faker-bot#178]
Still very new to Rails and am trying to use Faker to -- of course -- seed my userdata db with realistic-looking data. When I execute the code below via rails db:seed, I don't get any response from the CLI, rather just a returned line with no output, messaging, etc.

Seeds.rb:

```
require "faker"

10.times do
    data = Userdatum.new(
        adds1: Faker::Address.street_address,
        adds2: '-',
        addcity: Faker::Address.city,
        addstate: Faker::Address.state,
        addzip: Faker::Address.zip,
        phone: Faker::PhoneNumber.cell_phone,
        taxpref: Faker::Boolean.boolean,
        mtgepref: Faker::Boolean.boolean,
        inspref: Faker::Boolean.boolean,
        created_at: '123456',
        updated_at: '123456',
        user_id: 10000,
        fName: Faker::Name.first_name,
        lName: Faker::Name.last_name,
        email: Faker::Internet.email
    )
    data.save
end
```

Byebug error message:

```
[4, 13] in /Users/robertmaxwell/RUBY/GULF/GULF/db/seeds.rb
    4: # Examples:
    5: #
    6: #   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
    7: #   Character.create(name: 'Luke', movie: movies.first)
    8: 
=>  9: require "faker"
   10: 
   11: 10.times do
   12:     data = Userdatum.new(
   13:         adds1: Faker::Address.street_address,
```

Schema.db

ActiveRecord::Schema.define(version: 2021_07_26_050246) do

 ```
 create_table "userdata", force: :cascade do |t|
    t.string "adds1"
    t.string "adds2"
    t.string "addcity"
    t.string "addstate"
    t.string "addzip"
    t.string "phone"
    t.boolean "taxpref"
    t.boolean "mtgepref"
    t.boolean "inspref"
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
    t.integer "user_id"
    t.string "fName"
    t.string "lName"
    t.string "email"
    t.index ["user_id"], name: "index_userdata_on_user_id"
  end
```

Please, please, please and thank you in advance for any assistance here!

**Comment by akabiru** [comment]
Hey there @robertemaxwell , from the scenario shared above: rails loads the [faker](https://github.com/faker-ruby/faker) library(gem) i.e. require 'faker'. `faker-bot` is a command line application (CLI) that adds a `$ faker` command executibale on a terminal interface. See [example here in the tests](https://github.com/faker-ruby/faker-bot/blob/main/spec/integration/list_spec.rb#L4-L20). Hence the calls to `Faker::` namespace within a rails app are directed to the faker library, not faker bot. 🙂 

_Hope this was helpful and I wish you the best in your learning journey! Will go ahead and close this for now but feel free to respond if unclear. Cheers_
