### ISSUE TITLE
Let `faker list` accept arguments

### ISSUE THREAD

**Issue by akabiru** [akabiru/faker-bot#20]
### Description

At the moment running `faker list` will list out **all** Faker constants and the methods they respond to. This is cool and all but what if I just want to list `Faker::Internet`? 

I should be able to run sth like `faker list internet` and this should list out the `Faker::Internet` class

The command should also support the verbose option and any other sensible options e.g. data type.

<details><summary>Screenshot 📷 </summary>

![screenshot 2019-01-18 at 10 50 08](https://user-images.githubusercontent.com/17295175/51372638-e5c69680-1b0e-11e9-9e01-612fc996b2da.jpg)

</details>

**Comment by akabiru** [comment]
Moved to https://github.com/stympy/faker/issues/1569

**Comment by bpleslie** [comment]
@akabiru thoughts on closing this in favor of the `search` changes in #38 ?

**Comment by akabiru** [comment]
@bpleslie I think this is a separate piece of work. It's an enhancement on the `faker list` method.

**Comment by akabiru** [comment]
> @akabiru thoughts on closing this in favor of the `search` changes in #38 ?

Aaah, I see your point! From #38 you can run a `faker search Faker::Beer` and it'll achieve the functionality here.

For semantics, WDYT about adding the same functionality to the `faker list` command. i.e. `faker list Faker::Beer` 🤔

**Comment by bpleslie** [comment]
@akabiru I could see it added, but only if `faker list Faker::Beer` and `faker list Beer` match. In my opinion, we wouldn't need to support partial matches or lowercase queries for `list`. Thoughts?

**Comment by akabiru** [comment]
> @akabiru I could see it added, but only if `faker list Faker::Beer` and `faker list Beer` match. In my opinion, we wouldn't need to support partial matches or lowercase queries for `list`. Thoughts?

I agree, there would be no need to support partial matches. The user case I have in mind:

1.) User calls faker list
2.) User just wants to list out one of the classes, so they can call `faker list Beer` or `faker list Faker::Beer`

I'm very open to re-evaluating if this feature is useful. WDYT?

**Comment by bpleslie** [comment]
@akabiru I think this feature makes sense. I'm working on the code now 👍

**Comment by akabiru** [comment]
> @akabiru I think this feature makes sense. I'm working on the code now 👍

Much appreciated. 🙇

**Comment by bpleslie** [comment]
@akabiru you can probably un-pin this issue 😄
