### ISSUE TITLE
Fakerbot not searching namespace

### ISSUE THREAD

**Issue by akabiru** [akabiru/faker-bot#36]
> Example1:
> 
> ```
> C:\Users\richard.bulger>faker search beer -v
> 
> Sorry, we couldn't find a match 😢
> 
> 
> C:\Users\richard.bulger>faker search yeast -v
> Faker
> └── yeast=> 5526 - Brettanomyces lambicus
> Faker
> ├── as_you_like_it=> I like this place and willingly could waste my time in it.
> └── as_you_like_it_quote=> Can one desire too much of a good thing?.
> ```
> 
> Note that the first result for `beer` returns nothing. But the second for `yeast`, which is a method of `beer` does. (Also note that the namespace name isn't shown in the result tree, which I've raised in #1565 )
> 
> Also, in the second result, you can see it also returns irrelevant results from the Shakespeare namespace. Not sure why.
> 
> Example2:
> 
> ```
> C:\Users\richard.bulger>faker search simpsons -v
> Faker
> └── i_groups=> Two Two
> ```
> 
> Doesn't return any simpons namespace stuff, but returns a Kpop one...

From: https://github.com/stympy/faker/issues/1566

**Comment by bpleslie** [comment]
I'm able to reproduce this search issue. I'll dig in and report back 👍

**Comment by bpleslie** [comment]
This issue is resolved by the work in #38
