### ISSUE TITLE
Namespace missing in fakerbot

### ISSUE THREAD

**Issue by akabiru** [akabiru/faker-bot#37]
> ![image](https://user-images.githubusercontent.com/5989831/53959537-cd6d0400-40db-11e9-9241-ab53bcf5bb78.png)
> 
> Gem built from latest master. Windows 10, ruby 2.4.4p296 (2018-03-28 revision 63013) and ruby 2.5.3p105 (2018-10-18 revision 65156)
> 
> Expecting to see full namespace at top of tree, ie Faker::PhoneNumber (as shown in #1507 )

From: https://github.com/stympy/faker/issues/1565

**Comment by bpleslie** [comment]
I'm unable to reproduce the issue in ruby 2.4.0 or ruby 2.5.3 on MacOS Sierra 10.12.4

```
brad@WM00XXX-BLeslie faker-bot (master) $ bin/faker search phone -v
Faker::PhoneNumber
├── cell_phone=> 473-608-1850
├── cell_phone_with_country_code=> +503 1-306-753-7292
├── phone_number=> 1-485-375-6716 x85706
└── phone_number_with_country_code=> +47 155-965-6795
Faker::SouthAfrica
├── cell_phone=> +2776 908 4843
└── phone_number=> +2756 245 8958
brad@WM00XXX-BLeslie faker-bot (master) $ ruby -v
ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin16]
```
```
brad@WM00XXX-BLeslie faker-bot (master) $ bin/faker search phone -v
Faker::PhoneNumber
├── cell_phone=> 546.360.4663
├── cell_phone_with_country_code=> +599 (672) 651-4366
├── phone_number=> 931.882.7159 x357
└── phone_number_with_country_code=> +269 811.373.4484 x04564
Faker::SouthAfrica
├── cell_phone=> +2781 389 2356
└── phone_number=> 046 681 4986
brad@WM00XXX-BLeslie faker-bot (master) $ ruby -v
ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-darwin16]
```

Is there any chance this has been fixed since it was reported in March @akabiru? 🤔 Otherwise it may be a Windows issue..

**Comment by akabiru** [comment]
I think it's was reported as a Windows-specific issue, @richardbulger are you able to chime in here?

**Comment by akabiru** [comment]
> I'm unable to reproduce the issue in ruby 2.4.0 or ruby 2.5.3 on MacOS Sierra 10.12.4
> 
> ```
> brad@WM00XXX-BLeslie faker-bot (master) $ bin/faker search phone -v
> Faker::PhoneNumber
> ├── cell_phone=> 473-608-1850
> ├── cell_phone_with_country_code=> +503 1-306-753-7292
> ├── phone_number=> 1-485-375-6716 x85706
> └── phone_number_with_country_code=> +47 155-965-6795
> Faker::SouthAfrica
> ├── cell_phone=> +2776 908 4843
> └── phone_number=> +2756 245 8958
> brad@WM00XXX-BLeslie faker-bot (master) $ ruby -v
> ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin16]
> ```
> 
> ```
> brad@WM00XXX-BLeslie faker-bot (master) $ bin/faker search phone -v
> Faker::PhoneNumber
> ├── cell_phone=> 546.360.4663
> ├── cell_phone_with_country_code=> +599 (672) 651-4366
> ├── phone_number=> 931.882.7159 x357
> └── phone_number_with_country_code=> +269 811.373.4484 x04564
> Faker::SouthAfrica
> ├── cell_phone=> +2781 389 2356
> └── phone_number=> 046 681 4986
> brad@WM00XXX-BLeslie faker-bot (master) $ ruby -v
> ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-darwin16]
> ```
> 
> Is there any chance this has been fixed since it was reported in March @akabiru? 🤔 Otherwise it may be a Windows issue..

Resolving this issue as there have been no new reports- we can re-open if otherwise. 👍
