### ISSUE TITLE
Sort `fakerbot list` alphabetically

### ISSUE THREAD

**Issue by akabiru** [akabiru/faker-bot#4]
## Description

As it stands, calling 'fakerbot list' will list faker constants in an arbitrary order. This should be alphabetical.

**Comment by cato-hga** [comment]
@akabiru Is this issue still open? If so, I would love to tackle this one. This would be my first time contributing to OS.

**Comment by akabiru** [comment]
Heya @cato-hga , yes, it's still very open. 🙂Go for it!

**Comment by cato-hga** [comment]
@akabiru Awesome! Working on this now.

**Comment by amrrbakry** [comment]
@cato-hga hey man, are you still working on this? i can help you with it if you need any help

**Comment by cato-hga** [comment]
@amrrbakry Yes but I am stuck. Can we pair on this sometime soon?

**Comment by amrrbakry** [comment]
@cato-hga sure. let's talk here: https://discord.gg/SP9w2Dn

**Comment by akabiru** [comment]
Loving the collaboration here! Please feel free to give me a shout as well. 🙂

**Comment by akabiru** [comment]
Any update on this guys? I'm happy to give some pointers. 🙂

**Comment by amrrbakry** [comment]
I'm waiting for @cato-hga to tell me where he got stuck

**Comment by amrrbakry** [comment]
you may want to check the discord channel @cato-hga @akabiru

**Comment by amrrbakry** [comment]
@cato-hga I opened a PR for this issue. take a look #9
