### ISSUE TITLE
Define a Release Process

### ISSUE THREAD

**Issue by akabiru** [akabiru/faker-bot#40]
- [x] Add a `CHANGELOG.md` possibly use a tool for this, similar to Faker ❓ 
- [x] Add a `CONTRIBUTING.md` and include details on how releases are handled
- [x] Automated Semantic versioning ❓  https://github.com/semantic-release/semantic-release
- [x] Get feedback from Contributors cc @vbrazo @bpleslie

**Comment by vbrazo** [comment]
I think we should use the Rubygems.org suggestion regarding semantic versioning:

https://guides.rubygems.org/patterns/#semantic-versioning

**Comment by bpleslie** [comment]
I like the rails `CONTRIBUTING.md` https://github.com/rails/rails/blob/master/CONTRIBUTING.md. Short and sweet with links to more detailed resources.

**Comment by bpleslie** [comment]
Actually, can we just use the `faker` one? https://github.com/faker-ruby/faker/blob/master/CONTRIBUTING.md

**Comment by akabiru** [comment]
> Actually, can we just use the `faker` one? https://github.com/faker-ruby/faker/blob/master/CONTRIBUTING.md

This sounds great to me @bpleslie ! Apologies for the delayed response. Feel free to take this on if you're Ok. 🙂

**Comment by bpleslie** [comment]
@akabiru PR is up!

**Comment by akabiru** [comment]
Resolved by https://github.com/faker-ruby/faker-bot/pull/47
