### ISSUE TITLE
Faker Bot Logo Anyone? 🙃

### ISSUE THREAD

**Issue by akabiru** [akabiru/faker-bot#46]
### Description

Faker core has a very cool logo, I think it'd be really cool to have one for faker bot as well. 🙈

**Comment by vbrazo** [comment]
@Tobaloidee

**Comment by ngeshlew** [comment]
I'll take it on. Thanks @akabiru

**Comment by ngeshlew** [comment]
Finishing up on sketches then designing them on Illustrator

**Comment by akabiru** [comment]
Hi @ngeshlew 👋 😉

**Comment by ngeshlew** [comment]
> Hi @ngeshlew 👋 😉


Hey @akabiru as you know, workload was crazy. Now I'm back, I've started working on it 👇🏽

![Image of Faker Bot Logo ideation](https://uc3d7506f3ed2ab89cb496e73db4.previews.dropboxusercontent.com/p/thumb/ABAFCTmWn3chMEuZDEremee6v3PP4776UoS1EGRwkAsx_j5Fis__nBdFzIzvynN3crfLQbYq-jBF5cITKDpA8fZs75wcFFk7oJOJ3_AXwvQIcnjzWloNLicl9fDnbJm1JYOB9Aq00urQCaDWOWERnbazUuYx6MEzL1iywBRlW93O4sFyKon0lFo2-fpK4qm9zuwt2jkdHYT9CeWzP0zgh_vU1wuSg1Np6oomb_r5ko8W4scqh4A47Lr7P_xZnCt1wTcGxXjUUR-xwwrsoHZO31o2t7oAzylQGt5Pb2eatr3JxNQMzUsqDItgn62F-VI9Rl3JaTkO-OBfEZPVRPRwF-XmErXmTAKUP3u1IpgfRsapTqRglYcMf8OPF0mcuVks4retMabscviry72oazD0pMD39FOQYABupbx-BJXbWv516Q/p.png?fv_content=true&size_mode=5)

**Comment by akabiru** [comment]
> > Hi @ngeshlew 👋 😉
> 
> Hey @akabiru as you know, workload was crazy. Now I'm back, I've started working on it 👇🏽
> 
> ![Image of Faker Bot Logo ideation](https://camo.githubusercontent.com/7dd2696d500ebe5d5291744a228cfe5f4145d4694f37a1b72949df04602756eb/68747470733a2f2f756333643735303666336564326162383963623439366537336462342e70726576696577732e64726f70626f7875736572636f6e74656e742e636f6d2f702f7468756d622f4142414643546d576e3363684d45755a444572656d6565367633505034373736556f5331454752776b4173785f6a354669735f5f6e4264467a497a76796e4e336372664c516259712d6a4246356349544b44704138665a733735776346466b376f4a4f4a335f415877765149636e6a7a576c6f4e4c69636c3966446e624a6d314a594f423941713030757251436144574f5745526e62617a55755978364d457a4c3169797742526c5739334f347346794b6f6e306c466f322d66704b34716d397a757774326a6b64485954394365577a50307a67685f76553177755367314e70366f6f6d625f72356b6f38573473637168344134374c7237505f785a6e4374317754634778586a5555522d78777772736f485a4f33316f3274376f417a796c5147743550623265617472334a784e514d7a557371444974676e3632462d564939526c334a61546b4f2d4f4266455a505652505277462d586d4572586d54414b55503375314970676652736170547152676c59634d66384f5046306d6375566b73347265744d616273637669727937326f617a4430704d443339464f51594142757062782d424a58625776353136512f702e706e673f66765f636f6e74656e743d747275652673697a655f6d6f64653d35)

Yay! 🎉  Thanks @ngeshlew - it's looking great, can't wait! 😄

**Comment by ngeshlew** [comment]
@akabiru here you go...

### Background

- Faker as a brand has an aggressive look and feel hence the sharp edges as _posted in https://github.com/faker-ruby/faker/issues/1216#issuecomment-390261281_. On the other hand, if you look at bots, they are always friendly hence the smooth patterns on their brands. 

- Also, if you look at the Faker brand, it's like batman making Faker Bot, Robin. 

- Lastly, since Faker logo some sort of mask, Faker Bot is wearing it as well. 

### Design
I've created 6 variations, using the Orange Peel colour, of the same bot concept pegged on the above thinking to showcase the options 👇🏽 

**NB**: When giving feedback, you can label them as `[row, column]`, so like: _"I would like to see `[2, 3]` with the mask having a dark border..."_

![Faker Bot Logo from ngeshlew](https://ucd83e76662c568d515b3bc295f8.previews.dropboxusercontent.com/p/thumb/ABA_8TVQURoFmO9HxALF3Mte6GLC2EV8M8gLXR0ioXdTfgLI-lY-Y6rEizKxOOFbuB6tYmf2xJZm_4MKd7DZLLyp7CN0ZHXKA-0elw1cUZ125PkqOZHD5cVzJut87Peo0B8_09KPyHrrriEu9RngjgyiJmL4D0l0lMKrP5F5icxBZH0j3NprUhg81DFTE6QyiwEOV_jMhnHcKWdNyUlkWMFcfvTjgsfPgBLhWUvWv0UekPGuCXKyjOw2DaXbkz6kTF_s3lEmeDcsuWgVyurqH-dGDJ2inv2q-d9P1eMZArP_WxZOsqt33zP4khibpNo7VPVG7HpbTp1ATW_6UWAYslEm55xPuZaaavO-OrQpJTI_m-s5u4d5jj0M5Efh8RD3OSzBeHqlDT8v6P3TM94-MFAZefeoiAZ-XFB1WpKfYohofw/p.png?fv_content=true&size_mode=5)

### Next steps
We can vote for our preferences. You can use the key below (Github reactions) to indicate your favorite one:
- [1,1] => 👍
- [1,2] => 😆
- [1,3] => 🎉
- [2,1] => 😕
- [2,2] => ❤️
- [2,3] => 🚀

### Next step
Once we decide on the one that works for the project, I will create the rest using the Faker brand colours.

**Comment by akabiru** [comment]
> @akabiru here you go...
> 
> ### Background
> * Faker as a brand has an aggressive look and feel hence the sharp edges as _posted in [faker-ruby/faker#1216 (comment)](https://github.com/faker-ruby/faker/issues/1216#issuecomment-390261281)_. On the other hand, if you look at bots, they are always friendly hence the smooth patterns on their brands.
> * Also, if you look at the Faker brand, it's like batman making Faker Bot, Robin.
> * Lastly, since Faker logo some sort of mask, Faker Bot is wearing it as well.
> 
> ### Design
> I've created 6 variations, using the Orange Peel colour, of the same bot concept pegged on the above thinking to showcase the options 👇🏽
> 
> **NB**: When giving feedback, you can label them as `[row, column]`, so like: _"I would like to see `[2, 3]` with the mask having a dark border..."_
> 
> ![Faker Bot Logo from ngeshlew](https://camo.githubusercontent.com/f765f3fc8ff0625385c75853a70518d2e8815f3cdb4226d3f1320963dcebd5fa/68747470733a2f2f756364383365373636363263353638643531356233626332393566382e70726576696577732e64726f70626f7875736572636f6e74656e742e636f6d2f702f7468756d622f4142415f3854565155526f466d4f394878414c46334d746536474c43324556384d38674c585230696f58645466674c492d6c592d59367245697a4b784f4f466275423674596d6632784a5a6d5f344d4b6437445a4c4c797037434e305a48584b412d30656c773163555a313235506b714f5a48443563567a4a7574383750656f3042385f30394b50794872727269457539526e676a6779694a6d4c3444306c306c4d4b7250354635696378425a48306a334e70725568673831444654453651796977454f565f6a4d686e48634b57644e79556c6b574d46636676546a6773665067424c6857557657763055656b50477543584b796a4f7732446158626b7a366b54465f73336c456d654463737557675679757271482d6447444a32696e7632712d64395031654d5a4172505f57785a4f73717433337a50346b686962704e6f3756505647374870625470314154575f3655574159736c456d35357850755a616161764f2d4f7251704a54495f6d2d7335753464356a6a304d35456668385244334f537a426548716c44543876365033544d39342d4d46415a6566656f69415a2d5846423157704b66596f686f66772f702e706e673f66765f636f6e74656e743d747275652673697a655f6d6f64653d35)
> 
> ### Next steps
> We can vote for our preferences. You can use the key below (Github reactions) to indicate your favorite one:
> 
> * [1,1] => 👍
> * [1,2] => 😆
> * [1,3] => 🎉
> * [2,1] => 😕
> * [2,2] => ❤️
> * [2,3] => 🚀
> 
> ### Next step
> Once we decide on the one that works for the project, I will create the rest using the Faker brand colours.

Looking great @ngeshlew ! Spoilt for choice here 😄  Voted for `[1, 3]`.

@bpleslie @vbrazo wanna drop in your votes?

**Comment by akabiru** [comment]
> > @akabiru here you go...
> > ### Background
> > 
> > * Faker as a brand has an aggressive look and feel hence the sharp edges as _posted in [faker-ruby/faker#1216 (comment)](https://github.com/faker-ruby/faker/issues/1216#issuecomment-390261281)_. On the other hand, if you look at bots, they are always friendly hence the smooth patterns on their brands.
> > * Also, if you look at the Faker brand, it's like batman making Faker Bot, Robin.
> > * Lastly, since Faker logo some sort of mask, Faker Bot is wearing it as well.
> > 
> > ### Design
> > I've created 6 variations, using the Orange Peel colour, of the same bot concept pegged on the above thinking to showcase the options 👇🏽
> > **NB**: When giving feedback, you can label them as `[row, column]`, so like: _"I would like to see `[2, 3]` with the mask having a dark border..."_
> > ![Faker Bot Logo from ngeshlew](https://camo.githubusercontent.com/f765f3fc8ff0625385c75853a70518d2e8815f3cdb4226d3f1320963dcebd5fa/68747470733a2f2f756364383365373636363263353638643531356233626332393566382e70726576696577732e64726f70626f7875736572636f6e74656e742e636f6d2f702f7468756d622f4142415f3854565155526f466d4f394878414c46334d746536474c43324556384d38674c585230696f58645466674c492d6c592d59367245697a4b784f4f466275423674596d6632784a5a6d5f344d4b6437445a4c4c797037434e305a48584b412d30656c773163555a313235506b714f5a48443563567a4a7574383750656f3042385f30394b50794872727269457539526e676a6779694a6d4c3444306c306c4d4b7250354635696378425a48306a334e70725568673831444654453651796977454f565f6a4d686e48634b57644e79556c6b574d46636676546a6773665067424c6857557657763055656b50477543584b796a4f7732446158626b7a366b54465f73336c456d654463737557675679757271482d6447444a32696e7632712d64395031654d5a4172505f57785a4f73717433337a50346b686962704e6f3756505647374870625470314154575f3655574159736c456d35357850755a616161764f2d4f7251704a54495f6d2d7335753464356a6a304d35456668385244334f537a426548716c44543876365033544d39342d4d46415a6566656f69415a2d5846423157704b66596f686f66772f702e706e673f66765f636f6e74656e743d747275652673697a655f6d6f64653d35)
> > ### Next steps
> > We can vote for our preferences. You can use the key below (Github reactions) to indicate your favorite one:
> > 
> > * [1,1] => 👍
> > * [1,2] => 😆
> > * [1,3] => 🎉
> > * [2,1] => 😕
> > * [2,2] => ❤️
> > * [2,3] => 🚀
> > 
> > ### Next step
> > Once we decide on the one that works for the project, I will create the rest using the Faker brand colours.
> 
> Looking great @ngeshlew ! Spoilt for choice here 😄 Voted for `[1, 3]`.
> 
> @bpleslie @vbrazo wanna drop in your votes?

@ngeshlew vote still stands at `[1, 3]` wdyt? Ok to got with that one?

**Comment by ngeshlew** [comment]
@akabiru `[1,3]` works perfectly for me. I can fork the project and create a `design` folder and add them there then do a PR that closes this issue, wdyt?

**Comment by akabiru** [comment]
> @akabiru `[1,3]` works perfectly for me. I can fork the project and create a `design` folder and add them there then do a PR that closes this issue, wdyt?

Sounds great to me @ngeshlew ; please go right ahead. I reckon we'll also include some changes to the ReadMe and also the release script so that images are not baked into the gem (we can pair on this bit 🙂 ).

**Comment by akabiru** [comment]
No progress here, closing 🙂
