### ISSUE TITLE
Handle Deprecation Warnings

### ISSUE THREAD

**Issue by akabiru** [akabiru/faker-bot#7]
Lookups that include methods with deprecation warnings are currently not handled gracefully.

We should find a way of showing this nicely as it's still valuable info.

## Steps to reproduce bug
```
$ fakerbot list -v
```

![screen shot 2018-08-16 at 10 38 44](https://user-images.githubusercontent.com/17295175/44195161-e2367a00-a140-11e8-9cbe-5b51e845bc76.jpg)

### After pager exit 😭 

![screen shot 2018-08-16 at 10 38 35](https://user-images.githubusercontent.com/17295175/44195187-f2e6f000-a140-11e8-8bdf-f6e0a29de84f.jpg)

**Comment by shtakai** [comment]
The location of testing is `spec/integration/list_spec.rb line 27`.  🍣  😢 

```
alyson@HARDCORE ~/p/g/fakerbot> rspec ./spec/integration/list_spec.rb:27
[Coveralls] Set up the SimpleCov formatter.
[Coveralls] Using SimpleCov's default settings.
Run options: include {:locations=>{"./spec/integration/list_spec.rb"=>[27]}}

`fakerbot list command
NOTE: Faker::Name.title is deprecated; use Faker::Job.title instead. It will be removed on or after 2018-09-01.
Faker::Name.title called from /Users/alyson/project/gems/fakerbot/lib/fakerbot/renderer.rb:60.
NOTE: Faker::Name.job_titles is deprecated with no replacement. It will be removed on or after 2018-09-01.
Faker::Name.job_titles called from /Users/alyson/project/gems/fakerbot/lib/fakerbot/renderer.rb:60.
  executes `fakerbot list -v` command successfully

Finished in 8.14 seconds (files took 5.44 seconds to load)
1 example, 0 failures
```

**Comment by akabiru** [comment]
Thank you @shtakai! 🙂You're right, the deprecation warnings are triggered by the `--verbose` flag from calling methods with dep warnings https://github.com/akabiru/fakerbot/blob/master/lib/fakerbot/renderer.rb#L60

I think it'd be cool if we displayed the dep warnings in a more user friendly manner. E.g.

```
$ fakerbot list -v
Faker::SomeClass
├── a_method [deprecated use Faker::NewClass.a_method] => sample output
```

**Comment by shtakai** [comment]
@akabiru  Thank you. 😄 
On `Faker` gem, each file of like `Faker::ABCD` extends `Gem::Deprecate`.
And if there are deprecate method, add `deprecate` method.

```
[faker] ag deprecate --ruby
lib/faker/name.rb
8:      extend Gem::Deprecate
59:      deprecate :title, 'Faker::Job.title', 2018, 9
60:      deprecate :job_titles, :none, 2018, 9

lib/faker/educator.rb
8:      extend Gem::Deprecate
19:      deprecate :course, :course_name, 2018, 10
```
I think it's available to pick up these methods. 😄

**Comment by akabiru** [comment]
Awesome detective work @shtakai ! 🔍  Would you like to work on this issue? It'd be great of you would. 🙂

**Comment by shtakai** [comment]
I implemented checking deprecation like as follows.


```ruby
renderer.rb

    def leaf_args(method, const)
      [method.to_s].tap do |arr|
        if verbose?
          fake, deprecated = begin
            deprecate = const.respond_to?("_deprecated_#{method.to_s}".to_sym) ? ' ( WILL BE DEPRECATED )' : ''
            [const.public_send(method), deprecate]
          rescue ArgumentError
            ['N/A', '']
          end
          arr << crayon.dim.white("=> #{fake.to_s}#{deprecated}")
        end
      end
    end
```

The output is...

```
$ fakerbot list -v
:
:
Faker::Name
├── name=> Brett Metz
├── title=> Senior Legal Specialist ( WILL BE DEPRECATED )
├── _deprecated_title=> Legacy Advertising Assistant
└── _deprecated_job_titles=> ["Supervisor", "Associate", "Executive", "Liaison", "Officer",....]
:
```

But I am not sure how to track the `name after deprecation`.....

I'll clean code, refactor and make Pull Request. 😄

**Comment by akabiru** [comment]
Nice one!  This is a brilliant start. We can start with the `( WILL BE DEPRECATED )` message and figure out how to get the name after. 🥇 Looking forward to the PR. 😄

**Comment by shtakai** [comment]
@akabiru Thank you 😄
