### ISSUE TITLE
Should search include namespaces in addition to methods?

### ISSUE THREAD

**Issue by akabiru** [akabiru/faker-bot#8]
# Description
At the moment executing `fakerbot search star` does not include results like `Faker::StarWars` i.e. "everything matching `star`".
 This is because the [fakerbot reflector](https://github.com/akabiru/fakerbot/blob/master/lib/fakerbot/reflector.rb#L63) only searches through the class method names and doesn't include the class names.

## Task
Find a sensible way of implementing a "full" search i.e. one that includes the class and it's method names.

**Comment by Jdcorley** [comment]
Is this still available? Could I take this as a first time Open Source contribution?

Thanks!
Jack

**Comment by akabiru** [comment]
Hey @Jdcorley ,

Thanks for checking this out!

Go for it! and please shout if you have any questions.
🙂

**Comment by Jdcorley** [comment]
Hey @akabiru! 

So I've been poking around a bit with this and playing with ideas on how we could integrate the namespaces into the search. I've been able to pull up the namespaces in faker by calling:

`Faker.constants`

I'm just trying to read through the code a bit more and figure out a way to integrate them that makes sense. Let me know if you have any tips are suggestions.

Thanks!

**Comment by akabiru** [comment]
Hey @Jdcorley ,

Great to hear from you- and thanks for looking into this. FYI, fakerbot [has been merged into faker](https://github.com/stympy/faker/pull/1507) 

Are you Ok for us to move the conversation to faker?- there's an issue tracking this, and I think you're best placed to tackle it. 🙂 https://github.com/stympy/faker/issues/1566

**Comment by Jdcorley** [comment]
@akabiru awesome! yeah, let's move the conversation there.

**Comment by akabiru** [comment]
Done! 🎉
